name: paccmann_sets
channels:
  - conda-forge
dependencies:
  - python>=3.7,<3.8
  - pip>=19.1
  - pip:
    - numpy>=1.14.3
    - scipy>=1.3.1
    - pytoda @ git+https://github.com/PaccMann/paccmann_datasets@0.2.4
    - torch>=1.3.0
    - brc-pytorch >= 0.1.3
    - requests>=2.23.0
    # data analysis
    - pandas>=0.24.2,<1.0
    - scikit-learn==0.22.2
    - matplotlib>=3.1.1
    - seaborn>=0.9.0
    - astropy==4.0.1.post1
    - scikit-image==0.16.2
    - imageio==2.6.1
    # dev tools
    - pytest==5.4.2
 
